-- lua/plugins/init.lua

require('plugins.lualine')
require('plugins.bufferline')
require('plugins.nvim-tree')
require('plugins.treesitter')
require('plugins.gitsigns')
require('plugins.avante')
require('plugins.img-clip')
require('plugins.render-markdown')
require('plugins.project_nvim')
require('plugins.ufo')
require('plugins.gitsigns')
require('plugins.comment')
require('plugins.alpha')
require('plugins.telescope')
require('plugins.coc')
require('plugins.nvim_cmp')
require('plugins.vim_fugitive')
require('plugins.nui')
require('plugins.dressing')
require('plugins.plenary')
