local opt = vim.opt

opt.number = true
opt.relativenumber = true
opt.mouse = 'a'
opt.ignorecase = true
opt.smartcase = true
opt.hlsearch = false
opt.wrap = true
opt.breakindent = true
opt.tabstop = 4
opt.shiftwidth = 4
opt.softtabstop = 4
opt.expandtab = true
opt.smartindent = true
opt.autoindent = true
opt.smarttab = true
opt.termguicolors = true
opt.signcolumn = "yes"
opt.updatetime = 300
opt.timeoutlen = 400
opt.clipboard = "unnamedplus"
opt.undofile = true
opt.swapfile = false
opt.backup = false
opt.splitright = true
opt.splitbelow = true
opt.cursorline = true
opt.scrolloff = 8
opt.sidescrolloff = 8
opt.guifont = "JetBrainsMono Nerd Font:h12"

vim.g.mapleader = " "
vim.g.maplocalleader = " "
